const std = @import("std");

pub const Event = union(enum) {
    pub const Key = enum(u16) {
        a = 'A',
        b = 'B',
        c = 'C',
        d = 'D',
        e = 'E',
        f = 'F',
        g = 'G',
        h = 'H',
        i = 'I',
        j = 'J',
        k = 'K',
        l = 'L',
        m = 'M',
        n = 'N',
        o = 'O',
        p = 'P',
        q = 'Q',
        r = 'R',
        s = 'S',
        t = 'T',
        u = 'U',
        v = 'V',
        w = 'W',
        x = 'X',
        y = 'Y',
        z = 'Z',
        space = 32,
        escape = 256,
        enter = 257,
        tab = 258,
        backspace = 259,
        insert = 260,
        delete = 261,
        right = 262,
        left = 263,
        down = 264,
        up = 265,
        page_up = 266,
        page_down = 267,
        home = 268,
        end = 269,
        caps_lock = 280,
        scroll_lock = 281,
        num_lock = 282,
        print_screen = 283,
        pause = 284,
        f1 = 290,
        f2 = 291,
        f3 = 292,
        f4 = 293,
        f5 = 294,
        f6 = 295,
        f7 = 296,
        f8 = 297,
        f9 = 298,
        f10 = 299,
        f11 = 300,
        f12 = 301,
        f13 = 302,
        f14 = 303,
        f15 = 304,
        f16 = 305,
        f17 = 306,
        f18 = 307,
        f19 = 308,
        f20 = 309,
        f21 = 310,
        f22 = 311,
        f23 = 312,
        f24 = 313,
        f25 = 314,
        kp_0 = 320,
        kp_1 = 321,
        kp_2 = 322,
        kp_3 = 323,
        kp_4 = 324,
        kp_5 = 325,
        kp_6 = 326,
        kp_7 = 327,
        kp_8 = 328,
        kp_9 = 329,
        kp_decimal = 330,
        kp_divide = 331,
        kp_multiply = 332,
        kp_subtract = 333,
        kp_add = 334,
        kp_enter = 335,
        kp_equal = 336,
        left_shift = 340,
        left_control = 341,
        left_alt = 342,
        left_super = 343,
        right_shift = 344,
        right_control = 345,
        right_alt = 346,
        right_super = 347,
        menu = 348,
        _,
    };

    window_resize: struct { window: ?*Window, width: u32, height: u32 },
    window_close: ?*Window,
    window_focus: struct {
        window: ?*Window,
        focused: bool,
    },
    key_press: struct {
        window: ?*Window,
        key: Key,
        action: Action,
        mods: Modifiers,
    },
    mouse_press: struct {
        window: ?*Window,
        button: enum(u8) {
            left = 0,
            right = 1,
            middle = 2,
            _,
        },
        action: Action,
        mods: Modifiers,
    },
    mouse_move: struct {
        window: ?*Window,
        x: f64,
        y: f64,
    },
};

pub const Action = enum(u8) { release = 0, press = 1, repeat = 2 };
pub const Modifiers = packed struct(u8) {
    shift: u1 = 0,
    ctrl: u1 = 0,
    alt: u1 = 0,
    super: u1 = 0,
    caps: u1 = 0,
    num: u1 = 0,
    _pad: u2 = 0,
};

const Window = @import("window.zig").Window;
